In [ ]:
# !pip install scikit-learn

Collecting scikit-learn
  Downloading scikit_learn-1.9.1-cp312-cp312-win_amd64.whl.metadata (9.3 kB)
Requirement already satisfied: numpy>=1.24.1 in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from scikit-learn) (2.4.4)
Collecting scipy>=1.10.0 (from scikit-learn)
  Downloading scipy-1.18.1-cp312-cp312-win_amd64.whl.metadata (61 kB)
Collecting joblib>=1.4.0 (from scikit-learn)
  Downloading joblib-1.6.0-py3-none-any.whl.metadata (6.5 kB)
Collecting narwhals>=2.0.1 (from scikit-learn)
  Downloading narwhals-2.26.0-py3-none-any.whl.metadata (15 kB)
Collecting threadpoolctl>=3.5.0 (from scikit-learn)
  Downloading threadpoolctl-3.7.0-py3-none-any.whl.metadata (24 kB)
Collecting cloudpickle>=3.0 (from joblib>=1.4.0->scikit-learn)
  Downloading cloudpickle-3.1.2-py3-none-any.whl.metadata (7.1 kB)
Downloading scikit_learn-1.9.1-cp312-cp312-win_amd64.whl (8.3 MB)
   ---------------------------------------- 0.0/8.3 MB ? eta -:--:--
   ----- ---------------------------------- 1.0/8.3 MB 7.1 MB/s eta 0:00:02
   ------------ --------------------------- 2.6/8.3 MB 7.2 MB/s eta 0:00:01
   ---------------------- ----------------- 4.7/8.3 MB 8.1 MB/s eta 0:00:01
   ------------------------------- -------- 6.6/8.3 MB 8.4 MB/s eta 0:00:01
   ---------------------------------------- 8.3/8.3 MB 8.5 MB/s eta 0:00:00
Downloading joblib-1.6.0-py3-none-any.whl (306 kB)
Downloading narwhals-2.26.0-py3-none-any.whl (474 kB)
Downloading scipy-1.18.1-cp312-cp312-win_amd64.whl (36.7 MB)
   ---------------------------------------- 0.0/36.7 MB ? eta -:--:--
   - -------------------------------------- 1.0/36.7 MB 5.6 MB/s eta 0:00:07
   -- ------------------------------------- 2.1/36.7 MB 4.9 MB/s eta 0:00:08
   --- ------------------------------------ 2.9/36.7 MB 4.8 MB/s eta 0:00:08
   ---- ----------------------------------- 4.2/36.7 MB 4.8 MB/s eta 0:00:07
   ----- ---------------------------------- 5.0/36.7 MB 5.0 MB/s eta 0:00:07
   ------ --------------------------------- 5.8/36.7 MB 4.5 MB/s eta 0:00:07
   -------- ------------------------------- 7.3/36.7 MB 4.9 MB/s eta 0:00:07
   --------- ------------------------------ 8.4/36.7 MB 5.0 MB/s eta 0:00:06
   ---------- ----------------------------- 9.7/36.7 MB 5.1 MB/s eta 0:00:06
   ------------ --------------------------- 11.0/36.7 MB 5.2 MB/s eta 0:00:05
   ------------- -------------------------- 12.3/36.7 MB 5.3 MB/s eta 0:00:05
   -------------- ------------------------- 13.6/36.7 MB 5.4 MB/s eta 0:00:05
   ---------------- ----------------------- 14.9/36.7 MB 5.5 MB/s eta 0:00:04
   ------------------ --------------------- 16.5/36.7 MB 5.6 MB/s eta 0:00:04
   ------------------- -------------------- 17.8/36.7 MB 5.6 MB/s eta 0:00:04
   -------------------- ------------------- 19.1/36.7 MB 5.7 MB/s eta 0:00:04
   ---------------------- ----------------- 20.4/36.7 MB 5.7 MB/s eta 0:00:03
   ----------------------- ---------------- 21.5/36.7 MB 5.7 MB/s eta 0:00:03
   ------------------------ --------------- 22.3/36.7 MB 5.7 MB/s eta 0:00:03
   ------------------------- -------------- 23.3/36.7 MB 5.5 MB/s eta 0:00:03
   -------------------------- ------------- 24.4/36.7 MB 5.6 MB/s eta 0:00:03
   ---------------------------- ----------- 25.7/36.7 MB 5.6 MB/s eta 0:00:02
   ----------------------------- ---------- 27.3/36.7 MB 5.6 MB/s eta 0:00:02
   ------------------------------- -------- 28.6/36.7 MB 5.6 MB/s eta 0:00:02
   -------------------------------- ------- 29.4/36.7 MB 5.6 MB/s eta 0:00:02
   --------------------------------- ------ 30.4/36.7 MB 5.6 MB/s eta 0:00:02
   ---------------------------------- ----- 31.7/36.7 MB 5.6 MB/s eta 0:00:01
   ------------------------------------ --- 33.0/36.7 MB 5.6 MB/s eta 0:00:01
   ------------------------------------- -- 34.3/36.7 MB 5.7 MB/s eta 0:00:01
   -------------------------------------- - 35.7/36.7 MB 5.6 MB/s eta 0:00:01
   ---------------------------------------  36.4/36.7 MB 5.7 MB/s eta 0:00:01
   ---------------------------------------- 36.7/36.7 MB 5.6 MB/s eta 0:00:00
Downloading threadpoolctl-3.7.0-py3-none-any.whl (26 kB)
Downloading cloudpickle-3.1.2-py3-none-any.whl (22 kB)
Installing collected packages: threadpoolctl, scipy, narwhals, cloudpickle, joblib, scikit-learn
Successfully installed cloudpickle-3.1.2 joblib-1.6.0 narwhals-2.26.0 scikit-learn-1.9.1 scipy-1.18.1 threadpoolctl-3.7.0

[notice] A new release of pip is available: 25.0.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [3]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.model_selection import train_test_split

In [4]:
#load data
df = pd.read_csv('../data/telco_comm_churn.csv')
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [5]:
df['TotalCharges'] = pd.to_numeric(df['TotalCharges'], errors='coerce')

In [6]:
df.describe()

       SeniorCitizen       tenure  MonthlyCharges  TotalCharges
count    7043.000000  7043.000000     7043.000000   7032.000000
mean        0.162147    32.371149       64.761692   2283.300441
std         0.368612    24.559481       30.090047   2266.771362
min         0.000000     0.000000       18.250000     18.800000
25%         0.000000     9.000000       35.500000    401.450000
50%         0.000000    29.000000       70.350000   1397.475000
75%         0.000000    55.000000       89.850000   3794.737500
max         1.000000    72.000000      118.750000   8684.800000

In [7]:
df.isnull().sum()

customerID           0
gender               0
SeniorCitizen        0
Partner              0
Dependents           0
tenure               0
PhoneService         0
MultipleLines        0
InternetService      0
OnlineSecurity       0
OnlineBackup         0
DeviceProtection     0
TechSupport          0
StreamingTV          0
StreamingMovies      0
Contract             0
PaperlessBilling     0
PaymentMethod        0
MonthlyCharges       0
TotalCharges        11
Churn                0
dtype: int64

In [8]:
# df['TotalCharges'].fillna(df['TotalCharges'].median(), inplace=True)

df.fillna({'TotalCharges':df['TotalCharges'].median() }, inplace=True)

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.50,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,6840-RESVB,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,...,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.50,No
7039,2234-XADUH,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.90,No
7040,4801-JZAZL,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No
7041,8361-LTMKD,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.60,Yes
7042,3186-AJIEK,Male,0,No,No,66,Yes,No,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.50,No

In [10]:
df.isnull().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [11]:
df['tenure'].min(), df['tenure'].max()
df['tenure']

0        1
1       34
2        2
3       45
4        2
        ..
7038    24
7039    72
7040    11
7041     4
7042    66
Name: tenure, Length: 7043, dtype: int64

In [12]:
df['tenure_group'] = pd.cut(df['tenure'], 
       bins=[-1,12,24,48,73],
       labels = [0,1,2,3], 
       include_lowest = True)

In [13]:
df['tenure_group'].info()

<class 'pandas.Series'>
RangeIndex: 7043 entries, 0 to 7042
Series name: tenure_group
Non-Null Count  Dtype
--------------  -----
7043 non-null   category
dtypes: category(1)
memory usage: 7.0 KB

In [14]:
df['tenure_group'] = df['tenure_group'].astype(float).astype(int)
df['tenure_group'].info()

<class 'pandas.Series'>
RangeIndex: 7043 entries, 0 to 7042
Series name: tenure_group
Non-Null Count  Dtype
--------------  -----
7043 non-null   int64
dtypes: int64(1)
memory usage: 55.2 KB

In [15]:
df['avg_monthly_per_tenure'] = df['TotalCharges'] / (df['tenure'] + 1)

In [16]:
df.columns

Index(['customerID', 'gender', 'SeniorCitizen', 'Partner', 'Dependents',
       'tenure', 'PhoneService', 'MultipleLines', 'InternetService',
       'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport',
       'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling',
       'PaymentMethod', 'MonthlyCharges', 'TotalCharges', 'Churn',
       'tenure_group', 'avg_monthly_per_tenure'],
      dtype='str')

In [17]:
df = df.drop('customerID', axis = 1)

In [18]:
df.head(2)

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,...,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn,tenure_group,avg_monthly_per_tenure
0,Female,0,Yes,No,1,No,No phone service,DSL,No,Yes,...,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No,0,14.925000
1,Male,0,No,No,34,Yes,No,DSL,Yes,No,...,No,No,One year,No,Mailed check,56.95,1889.50,No,2,53.985714

In [19]:
binary_cols = ['Partner', 'Dependents', 'PhoneService', 'PaperlessBilling']
for col in binary_cols:
    df[col] = df[col].map({'Yes':1, 'No':0})
    
df.head(1)

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,...,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn,tenure_group,avg_monthly_per_tenure
0,Female,0,1,0,1,0,No phone service,DSL,No,Yes,...,No,No,Month-to-month,1,Electronic check,29.85,29.85,No,0,14.925

In [20]:
df['Churn'] = df['Churn'].map({'Yes':1,'No':0})

In [21]:
df['gender'] = df['gender'].map({'Male':1,'Female':0})

In [23]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 22 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   gender                  7043 non-null   int64
 1   SeniorCitizen           7043 non-null   int64
 2   Partner                 7043 non-null   int64
 3   Dependents              7043 non-null   int64
 4   tenure                  7043 non-null   int64
 5   PhoneService            7043 non-null   int64
 6   MultipleLines           7043 non-null   str
 7   InternetService         7043 non-null   str
 8   OnlineSecurity          7043 non-null   str
 9   OnlineBackup            7043 non-null   str
 10  DeviceProtection        7043 non-null   str
 11  TechSupport             7043 non-null   str
 12  StreamingTV             7043 non-null   str
 13  StreamingMovies         7043 non-null   str
 14  Contract                7043 non-null   str
 15  PaperlessBilling        7043 non-null   int64
 16  PaymentMethod           7043 non-null   str
 17  MonthlyCharges          7043 non-null   float64
 18  TotalCharges            7043 non-null   float64
 19  Churn                   7043 non-null   int64
 20  tenure_group            7043 non-null   int64
 21  avg_monthly_per_tenure  7043 non-null   float64
dtypes: float64(3), int64(9), str(10)
memory usage: 1.2 MB

In [24]:
categorical_cols = df.select_dtypes(include=['object']).columns.tolist()

C:\Users\user\AppData\Local\Temp\ipykernel_12192\4270898778.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_cols = df.select_dtypes(include=['object']).columns.tolist()

In [25]:
for col in categorical_cols:
    le = LabelEncoder()
    
    df[col] = le.fit_transform(df[col].astype(str))

In [26]:
df.head()

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,...,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn,tenure_group,avg_monthly_per_tenure
0,0,0,1,0,1,0,1,0,0,2,...,0,0,0,1,2,29.85,29.85,0,0,14.925000
1,1,0,0,0,34,1,0,0,2,0,...,0,0,1,0,3,56.95,1889.50,0,2,53.985714
2,1,0,0,0,2,1,0,0,2,2,...,0,0,0,1,3,53.85,108.15,1,0,36.050000
3,1,0,0,0,45,0,1,0,2,0,...,0,0,1,0,0,42.30,1840.75,0,2,40.016304
4,0,0,0,0,2,1,0,1,0,0,...,0,0,0,1,2,70.70,151.65,1,0,50.550000